# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: 'utf8'
  pool: 5
  port: 5432
  host: 'localhost'
  username: user123
  password: password123

development:
  <<: *default
  database: database_development

test:
  <<: *default
  database: database_test

production:
  <<: *default
  database: database_production
